### ISSUE TITLE
Crashes on Fabric Loader 0.16

### ISSUE THREAD

**Issue by FaultyFunctions** [Estecka/mc-Backburner#6]
Here is the crash log: https://mclo.gs/LQqeUY2

Minecraft Version: 1.21
Fabric Version: 0.100.7+1.21
Fabric Loader Version: 0.16.0
Back-burner Version: 1.3.4+1.21

**Comment by Estecka** [comment]
If my intuition is correct, it looks like some of my cursed mixins broke with the latest version of Mixin.

Should be an easy fix, but I won't be able to get a closer look at this for some days.
For the time being, downgrading to any version of Fabric Loader 0.15.x should be able to work around this.

**Comment by FaultyFunctions** [comment]
Thanks for the quick reply, I'm in no rush so I'll wait for the fix whenever you get a chance. Thanks again!

**Comment by Estecka** [comment]
Fixed in v1.3.5
