### ISSUE TITLE
[Suggestions] Less programmer centric commands

### ISSUE THREAD

**Issue by FaultyFunctions** [Estecka/mc-Backburner#7]
As a programmer I fully understand what all the commands do but I feel like people who aren't familiar with programming might get confused at the `pop` and `push` commands. I think these should be replaced or at least an alias added for `add` and `remove`. Below are my suggestions:

- `/note add <text>` or `/note write <text>` or similar (does the same thing as `/note queue <text>`, add note to bottom)
- `/note remove <index>` or `/note erase <index>` or similar (does the same thing as `/note pop <index>` but would require an index be specified)
- - Ability to write `last`, `first`, or `all` in place of an `<index>` number for `/note remove`.

**Comment by Estecka** [comment]
Agreed. Although I'm a bit surprised this was never mentionned it until now.
`remove <index>` already exists as you described; adding more aliases like this won't be too technically challenging. 

The reason I've been holding them up, is that I wanted to find names that are very explicit about which end of the list is being modified. For example, you proposed `write` as an alias to `queue`, but I originally considered it for `push` instead, which I use much more often. People may naturally gravitate toward either a fifo or lifo mentality; optimally there would be clear aliases for both of these.

`add` I think would work great as a shorthand for `insert`, with `add first` and `add last` being very concise and unambiguous.

**Comment by FaultyFunctions** [comment]
I guess it depends on how you think about the list. I would personally see it as a list written in a physical notebook or journal, so naturally `write` or `add` would add items to the bottom of the list because that's how people generally write. Though, if you view it as more of a digital interface, I can see the argument for adding things to the top of the list as the default.

I don't necessarily think `insert` needs an alias, it's pretty concise already but adding an alias for it it wouldn't really hurt. Though the subcommands `/note insert first` and `/note insert last` (or add) would be a great addition (along with adding `first` and `last` as subcommands to `/note remove`)

You *could* also go the route of letting people define their own aliases. Since you already allow them to change the root command, it wouldn't be much of a stretch to let them change specific sub commands as well.

**Comment by Estecka** [comment]
`first` and `last` I plan to include everywhere they would make sense.

Customizable aliases I think would receive little use, and would require more work to implement properly than the root command.  The default root was chosen for ease-of-use, but as a result could easily conflict with another mod; the only reason it can be changed at all is for compatibility.

The "notebook" theme didn't exist at first; the mod was originally conceptualized as a sort of personal questlog. It did take a lot of inspiration from `git stash`, but even in physical form, I vizualize this more as a pile of papers or sticky notes, stacked face up on top of one another.
On that aspect, the mod does have a sort of identity-crisis...

**Comment by Estecka** [comment]
Most of this is now available in v1.4

I went with `clear` instead of `remove all`. It was easier to implement, and I believe it's less likely to be used on accident.
